# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/actions.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'proto/actions.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13proto/actions.proto\x1a\x1bgoogle/protobuf/empty.proto\"5\n\rToggleRequest\x12\x14\n\x0cservice_name\x18\x01 \x01(\t\x12\x0e\n\x06\x65nable\x18\x02 \x01(\x08\" \n\x0eToggleResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\"\x1c\n\x0bLogResponse\x12\r\n\x05lines\x18\x01 \x03(\t2\xed\x02\n\rDeviceActions\x12\x30\n\rToggleService\x12\x0e.ToggleRequest\x1a\x0f.ToggleResponse\x12\x38\n\x06Reboot\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\x12=\n\x0b\x44oSoftReset\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\x12=\n\x0b\x44oHardReset\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\x12\x34\n\x0cGetDeviceLog\x12\x16.google.protobuf.Empty\x1a\x0c.LogResponse\x12<\n\nResetState\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Emptyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.actions_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TOGGLEREQUEST']._serialized_start=52
  _globals['_TOGGLEREQUEST']._serialized_end=105
  _globals['_TOGGLERESPONSE']._serialized_start=107
  _globals['_TOGGLERESPONSE']._serialized_end=139
  _globals['_LOGRESPONSE']._serialized_start=141
  _globals['_LOGRESPONSE']._serialized_end=169
  _globals['_DEVICEACTIONS']._serialized_start=172
  _globals['_DEVICEACTIONS']._serialized_end=537
# @@protoc_insertion_point(module_scope)
