# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/device.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'proto/device.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12proto/device.proto\x1a\x1bgoogle/protobuf/empty.proto\"J\n\x0eSWInfoResponse\x12\x0f\n\x07version\x18\x01 \x01(\t\x12\x12\n\nbuild_date\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\"S\n\x0eHWInfoResponse\x12\x16\n\x0esensor_version\x18\x01 \x01(\t\x12\x12\n\nmodel_type\x18\x02 \x01(\t\x12\x15\n\rserial_number\x18\x03 \x01(\t2{\n\rDeviceService\x12\x34\n\tGetSWInfo\x12\x16.google.protobuf.Empty\x1a\x0f.SWInfoResponse\x12\x34\n\tGetHWInfo\x12\x16.google.protobuf.Empty\x1a\x0f.HWInfoResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.device_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SWINFORESPONSE']._serialized_start=51
  _globals['_SWINFORESPONSE']._serialized_end=125
  _globals['_HWINFORESPONSE']._serialized_start=127
  _globals['_HWINFORESPONSE']._serialized_end=210
  _globals['_DEVICESERVICE']._serialized_start=212
  _globals['_DEVICESERVICE']._serialized_end=335
# @@protoc_insertion_point(module_scope)
